my_tuple=(13,23,34,43,32,21)
my_tuple2=(1,2,3,4,5)
print(my_tuple)
print(my_tuple*3)
print(3 in my_tuple)
print(3 not in my_tuple)
print(len(my_tuple))        
print(max(my_tuple))
print(min(my_tuple))
print(sum(my_tuple))
print(sorted(my_tuple))
print(tuple(reversed(my_tuple)))
print(my_tuple+my_tuple2)


