import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('Exam_score.csv')
print(df.info())
print(df.describe())
print(df.isnull().sum())
print(df.columns)
plt.figure(figsize=(10,6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()
plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x='study_hours', y='exam_score', hue='course')
plt.title('Study Hours vs Exam Score by Course')
plt.xlabel('Study Hours')
plt.ylabel('Exam Score')
plt.show()
plt.figure(figsize=(10,6))
sns.barplot(data=df, x='course', y='exam_score')
plt.title('Exam Score Distribution by Course')
plt.xlabel('Course')
plt.ylabel('Exam Score')
plt.show()
plt.figure(figsize=(10,6))
sns.barplot(data=df, x='study_method', y='exam_score', ci=None)         
plt.title('Average Exam Score by Study Method')
plt.xlabel('Study Method')
plt.ylabel('Average Exam Score')
plt.show()  
plt.figure(figsize=(10,6))
sns.lineplot(data=df, x='class_attendance', y='exam_score', marker='o')
plt.title('Class Attendance vs Exam Score')
plt.xlabel('Class Attendance (%)')
plt.ylabel('Exam Score')
plt.show()  
plt.figure(figsize=(10,6))
sns.violinplot(data=df, x='gender', y='exam_score')
plt.title('Exam Score Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Exam Score')
plt.show()